(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var aa=this||self;function f(a,b){a=a.split(".");var c=aa;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b}
function h(a,b){function c(){}c.prototype=b.prototype;a.l=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.h=function(d,g,e){for(var p=Array(arguments.length-2),v=2;v<arguments.length;v++)p[v-2]=arguments[v];return b.prototype[g].apply(d,p)}};function k(){}var ba="function"==typeof Uint8Array;function l(a,b,c){a.c=null;b||(b=[]);a.j=void 0;a.f=-1;a.a=b;a:{if(b=a.a.length){--b;var d=a.a[b];if(!(null===d||"object"!=typeof d||Array.isArray(d)||ba&&d instanceof Uint8Array)){a.g=b-a.f;a.b=d;break a}}a.g=Number.MAX_VALUE}a.i={};if(c)for(b=0;b<c.length;b++)d=c[b],d<a.g?(d+=a.f,a.a[d]=a.a[d]||m):(n(a),a.b[d]=a.b[d]||m)}var m=[];function n(a){var b=a.g+a.f;a.a[b]||(a.b=a.a[b]={})}
function q(a,b){if(b<a.g){b+=a.f;var c=a.a[b];return c!==m?c:a.a[b]=[]}if(a.b)return c=a.b[b],c===m?a.b[b]=[]:c}function r(a,b){a=q(a,b);return null==a?a:!!a}function ca(a){a=q(a,3);return null==a?0:a}function t(a,b){a=r(a,b);return null==a?!1:a}function u(a,b,c){b<a.g?a.a[b+a.f]=c:(n(a),a.b[b]=c);return a}function w(a,b,c,d){c!==d?u(a,b,c):b<a.g?a.a[b+a.f]=null:(n(a),delete a.b[b]);return a}function x(a,b,c){a.c||(a.c={});if(!a.c[c]){var d=q(a,c);d&&(a.c[c]=new b(d))}return a.c[c]}
function y(a,b,c){a.c||(a.c={});var d;c?d=c.a:d=c;a.c[b]=c;return u(a,b,d)}function z(a,b){return new a(b?JSON.parse(b):null)}k.prototype.toString=function(){return this.a.toString()};function A(a){l(this,a,da)}h(A,k);var da=[17];function B(a){l(this,a,ea)}h(B,k);var ea=[8];function C(a){l(this,a,fa)}h(C,k);var fa=[27];function D(a){l(this,a,ha)}h(D,k);var ha=[1,2,3];function E(a){l(this,a,null)}h(E,k);function F(a){l(this,a,null)}h(F,k);function G(a){l(this,a,ia)}h(G,k);function H(a){l(this,a,null)}h(H,k);var ia=[13];function I(a){l(this,a,ja)}h(I,k);var ja=[8];function J(a){l(this,a,ka)}h(J,k);var ka=[12];function K(a,b){a=a.getElementsByTagName("META");for(let c=0;c<a.length;++c)if(a[c].getAttribute("name")===b)return a[c].getAttribute("content")||"";return""};function L(a,b){b=new CustomEvent(b);a.a.dispatchEvent(b)}
class la{constructor(a){this.a=a;var b=K(a,"namespace");if(!b){b="ns-"+Math.random().toString(36).substr(2,5);a:{var c=a.getElementsByTagName("META");for(let d=0;d<c.length;++d)if("namespace"===c[d].getAttribute("name")&&c[d].getAttribute("index")===(0).toString()){c[d].setAttribute("content",b);break a}c=a.querySelector("#mys-meta");c||(c=document.createElement("div"),c.id="mys-meta",c.style.position="absolute",c.style.display="none",a.appendChild(c));a=document.createElement("META");a.setAttribute("name",
"namespace");a.setAttribute("content",b);a.setAttribute("index",(0).toString());c.appendChild(a)}}}};function M(a){var b=document;a=String(a);"application/xhtml+xml"===b.contentType&&(a=a.toLowerCase());return b.createElement(a)};function N(a){if(1>=a.b.offsetWidth||1>=a.b.offsetHeight)return!1;a.a.remove();L(a.c,"spanReady");return!0}
class ma{constructor(a,b){this.c=a;this.f=b;this.b=M("SPAN");this.b.style.fontSize="6px";this.b.textContent="go";this.a=M("DIV");this.a.style.position="absolute";this.a.style.top="100%";this.a.style.left="100%";this.a.style.width="1px";this.a.style.height="0";this.a.style.overflow="hidden";this.a.style.visibility="hidden";this.a.appendChild(this.b)}wait(){if(t(this.f,1))return null;L(this.c,"spanStart");this.c.a.appendChild(this.a);return N(this)?null:new Promise(a=>{const b=setInterval(()=>{N(this)&&
(clearInterval(b),a())},ca(this.f))})}};function O(a){a.b&=-31}function P(a,b){a.b|=b}class na{constructor(a,b){this.a=a;this.c=b;new J;this.b=0}f(){}};function Q(a,b,c){if(b&&c){const d=x(a.a.c,G,6);w(d,2,b,0);w(d,3,c,0)}z(D,K(a.b.a,"engine_msg")||"[]");return a.a.f()||Promise.resolve()}function oa(a){O(a.a);P(a.a,1);window.AFMA_Communicator&&window.AFMA_Communicator.addEventListener("onshow",()=>{P(a.a,32)});let b=0;const c=a.b.a;c.addEventListener("browserRender",()=>{++b;if(1==b)L(a.b,"overallStart"),Q(a).then(()=>{L(a.b,"overallQuiet")});else{var d=c.clientWidth,g=c.clientHeight;d&&g&&Q(a,d,g)}})}
class pa{constructor(a,b,c){this.b=new la(a);a=new I(b);this.a=c(this.b,a)}};function qa(a){a.c.length=0;a.b=!0}function R(a,b=null){a.a=!0;const c=()=>{a.b=!1;const d=a.c.shift();return void 0===d?(a.a=!1,Promise.resolve()):R(a,d())};return b?b.then(c,()=>{if(a.b)return c();a.a=!1;return Promise.reject()}):c()}function ra(a,b){for(const c of b)a.c.push(c);return a.a?null:R(a)}class sa{constructor(){this.b=this.a=!1;this.c=[]}};var S={};function T(){if(S!==S)throw Error("Bad secret");};function U(){var a="undefined"!==typeof window?window.trustedTypes:void 0;return null!==a&&void 0!==a?a:null};var V,ta=class{};class ua extends ta{constructor(){var a=null!==W&&void 0!==W?W:"";super();T();this.a=a}toString(){return this.a.toString()}}var W=null===(V=U())||void 0===V?void 0:V.emptyHTML;new ua;var X,va=class{};class wa extends va{constructor(){var a=null!==Y&&void 0!==Y?Y:"";super();T();this.a=a}toString(){return this.a.toString()}}var Y=null===(X=U())||void 0===X?void 0:X.emptyScript;new wa;var xa=class{};class Z extends xa{constructor(a){super();T();this.a=a}toString(){return this.a}};new Z("about:blank");new Z("about:invalid#zTSz");class ya extends na{constructor(a,b){super(a,b);this.g=new sa}f(){qa(this.g);return ra(this.g,[()=>null,()=>{{var a=null;const b=x(x(this.c,G,6),F,1);b&&(a=(new ma(this.a,b)).wait());L(this.a,"browserStart");L(this.a,"browserStartEnd");O(this);P(this,2)}return a},()=>{L(this.a,"browserReady");L(this.a,"browserReadyEnd");P(this,4);L(this.a,"overallReady");return null},()=>{L(this.a,"browserQuiet");L(this.a,"browserQuietEnd");P(this,8);return null}])}}
(function(a){let b=null;f("mys.engine.init",(c,d)=>{c=z(I,K(d,"render_config")||"[]");b=new pa(d,c.a,a);oa(b)});f("mys.engine.stage",()=>b?b.a.b:0)})(function(a,b){if(null!=q(b,6))var c=x(b,G,6);else{c=x(b,C,1);var d=x(b,B,12)||new B;var g=new H;var e=q(c,42);e=null==e?e:+e;g=w(g,1,(null==e?0:e)||1,0);r(d,17)&&(e=w(g,2,!0,!1),w(e,3,!0,!1));r(d,18)&&w(g,2,!0,!1);r(d,19)&&w(g,3,!0,!1);e=new G;var p=r(d,6)||!1;e=w(e,10,p,!1);p=q(d,2)||0;e=w(e,7,p,0);p=r(d,15)||!1;e=w(e,18,p,!1);g=y(e,23,g);e=q(d,20)||
0;0<e&&w(g,24,e,0);e=new F;e=w(e,3,100,0);e=w(e,4,1E4,0);r(d,4)?(w(e,6,!0,!1),w(e,7,"monospace",""),w(e,8,"IMWimw0.!?@","")):(r(d,5)&&w(e,9,!0,!1),w(e,5,!0,!1));y(g,1,e);e=new E;x(c,A,10)&&t(x(c,A,10),6)&&w(e,1,!0,!1);t(c,16)&&!r(d,1)&&w(e,2,!0,!1);y(g,4,e);c=g}y(b,6,c);return new ya(a,b)});}).call(this);
