(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';function l(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ca=ba(this);function n(a,b){if(b)a:{var c=ca;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&aa(c,a,{configurable:!0,writable:!0,value:b})}}
function p(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:l(a)}}n("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});n("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});
n("String.prototype.includes",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return-1!==this.indexOf(b,c||0)}});var da=this||self;
function q(a,b){function c(){}c.prototype=b.prototype;a.l=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.j=function(d,e,f){for(var g=Array(arguments.length-2),k=2;k<arguments.length;k++)g[k-2]=arguments[k];return b.prototype[e].apply(d,g)}};var r=0,t=0;function u(){this.a=[]}u.prototype.length=function(){return this.a.length};function v(a){var b=a.a;a.a=[];return b}function w(a,b){for(;127<b;)a.a.push(b&127|128),b>>>=7;a.a.push(b)}function x(a,b){if(0<=b)w(a,b);else{for(var c=0;9>c;c++)a.a.push(b&127|128),b>>=7;a.a.push(1)}}function y(a,b){a.a.push(b>>>0&255);a.a.push(b>>>8&255);a.a.push(b>>>16&255);a.a.push(b>>>24&255)};var A={},B=null;function ea(){this.c=[];this.b=0;this.a=new u}function C(a,b){w(a.a,8*b+2);b=v(a.a);a.c.push(b);a.b+=b.length;b.push(a.b);return b}function D(a,b){var c=b.pop();for(c=a.b+a.a.length()-c;127<c;)b.push(c&127|128),c>>>=7,a.b++;b.push(c);a.b++}function E(a,b,c){null!=c&&(w(a.a,8*b),x(a.a,c))}function F(a,b,c){null!=c&&(c=parseInt(c,10),w(a.a,8*b),x(a.a,c))}
function G(a,b,c){if(null!=c){b=C(a,b);for(var d=a.a,e=0;e<c.length;e++){var f=c.charCodeAt(e);if(128>f)d.a.push(f);else if(2048>f)d.a.push(f>>6|192),d.a.push(f&63|128);else if(65536>f)if(55296<=f&&56319>=f&&e+1<c.length){var g=c.charCodeAt(e+1);56320<=g&&57343>=g&&(f=1024*(f-55296)+g-56320+65536,d.a.push(f>>18|240),d.a.push(f>>12&63|128),d.a.push(f>>6&63|128),d.a.push(f&63|128),e++)}else d.a.push(f>>12|224),d.a.push(f>>6&63|128),d.a.push(f&63|128)}D(a,b)}};function H(){}var fa="function"==typeof Uint8Array;function I(a,b,c,d){a.a=null;b||(b=[]);a.i=void 0;a.c=-1;a.f=b;a:{if(b=a.f.length){--b;var e=a.f[b];if(!(null===e||"object"!=typeof e||Array.isArray(e)||fa&&e instanceof Uint8Array)){a.g=b-a.c;a.b=e;break a}}a.g=Number.MAX_VALUE}a.h={};if(c)for(b=0;b<c.length;b++)e=c[b],e<a.g?(e+=a.c,a.f[e]=a.f[e]||J):(K(a),a.b[e]=a.b[e]||J);if(d&&d.length)for(b=0;b<d.length;b++)L(a,d[b])}var J=[];function K(a){var b=a.g+a.c;a.f[b]||(a.b=a.f[b]={})}
function M(a,b){if(b<a.g){b+=a.c;var c=a.f[b];return c!==J?c:a.f[b]=[]}if(a.b)return c=a.b[b],c===J?a.b[b]=[]:c}function N(a,b,c){b<a.g?a.f[b+a.c]=c:(K(a),a.b[b]=c);return a}function O(a,b,c,d){(c=L(a,c))&&c!==b&&void 0!==d&&(a.a&&c in a.a&&(a.a[c]=void 0),N(a,c,void 0));N(a,b,d)}function L(a,b){for(var c,d,e=0;e<b.length;e++){var f=b[e],g=M(a,f);null!=g&&(c=f,d=g,N(a,f,void 0))}return c?(N(a,c,d),c):0}H.prototype.toString=function(){return this.f.toString()};function P(a){I(this,a,null,Q)}q(P,H);var Q=[[1,2,3],[4,5]];function R(a){I(this,a,ha,null)}q(R,H);var ha=[1];function ia(a,b,c,d){this.i=a;this.h=c;this.g=b;this.a=[];this.b=[];this.c=d}function S(a,b,c,d){a.h.includes(d)&&a.a.push({key:b,value:c,channel:d})}function T(a,b,c,d){var e=new P;isNaN(a)?O(e,3,Q[0],a):d?O(e,1,Q[0],Number(a)):O(e,2,Q[0],Number(a));"number"===typeof b?O(e,4,Q[1],b):O(e,5,Q[1],b);c&&N(e,6,c);return e};function U(){this.a=null;this.i=Date.now();this.h=this.g=!1;this.b=[]}U.prototype.init=function(a,b,c,d,e){var f=this;this.a=new ia(a,c,b,e);if(d){for(var g in d)this.a.b.push({key:g,value:d[g]});isNaN(d[5])||(this.g=!0,setInterval(this.c.bind(this),Number(d[5])),setTimeout(function(){V(f,"timeout")},3E5),document.addEventListener("visibilitychange",function(){"hidden"===document.visibilityState&&V(f,"document_hidden")}),window.addEventListener("beforeunload",function(){V(f,"beforeunload")}))}};
U.prototype.getBaseTime=function(){return this.i};U.prototype.setData=function(a,b,c){S(this.a,a,b,c);this.b[c]?this.b[c]++:this.b[c]=1};U.prototype.setAttribute=function(a,b){this.a.b.push({key:a,value:b})};U.prototype.send=function(){this.g||this.c()};
U.prototype.c=function(){if(0<this.a.a.length){for(var a=this.a,b=[],c=p(a.b),d=c.next();!d.done;d=c.next())d=d.value,b.push(T(d.key,d.value,void 0,!0));c=p(a.a);for(d=c.next();!d.done;d=c.next())d=d.value,b.push(T(d.key,d.value,d.channel,!1));c=new R;d=N(c,2,a.i);d=N(d,4,a.g);d.a||(d.a={});b=b||[];for(var e=[],f=0;f<b.length;f++)e[f]=b[f].f;d.a[1]=b;N(d,1,e);a.c&&N(c,5,a.c);a=new ea;c.a||(c.a={});if(!c.a[1]){b=M(c,1);d=[];for(e=0;e<b.length;e++)d[e]=new P(b[e]);c.a[1]=d}b=c.a[1];b==J&&(b=c.a[1]=
[]);if(0<b.length&&null!=b)for(d=0;d<b.length;d++){e=C(a,1);f=b[d];var g=M(f,1);null!=g&&F(a,1,g);g=M(f,2);null!=g&&F(a,2,g);g=M(f,3);null!=g&&G(a,3,g);g=M(f,4);if(null!=g){var k=g;if(null!=k){w(a.a,33);g=a.a;var h=k;h=(k=0>h?1:0)?-h:h;if(0===h)t=0<1/h?0:2147483648,r=0;else if(isNaN(h))t=2147483647,r=4294967295;else if(1.7976931348623157E308<h)t=(k<<31|2146435072)>>>0,r=0;else if(2.2250738585072014E-308>h)h/=Math.pow(2,-1074),t=(k<<31|h/4294967296)>>>0,r=h>>>0;else{var z=h,m=0;if(2<=z)for(;2<=z&&
1023>m;)m++,z/=2;else for(;1>z&&-1022<m;)z*=2,m--;h*=Math.pow(2,-m);t=(k<<31|m+1023<<20|1048576*h&1048575)>>>0;r=4503599627370496*h>>>0}y(g,r);y(g,t)}}g=M(f,5);null!=g&&G(a,5,g);g=M(f,6);null!=g&&null!=g&&E(a,6,g);D(a,e)}b=M(c,2);null!=b&&G(a,2,b);b=M(c,3);null!=b&&null!=b&&E(a,3,b);b=M(c,4);null!=b&&G(a,4,b);b=M(c,5);null!=b&&null!=b&&E(a,5,b);c=new Uint8Array(a.b+a.a.length());d=a.c;e=d.length;for(f=b=0;f<e;f++)g=d[f],c.set(g,b),b+=g.length;d=v(a.a);c.set(d,b);a.c=[c];a=void 0;void 0===a&&(a=0);
if(!B)for(B={},b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],e=0;5>e;e++)for(f=b.concat(d[e].split("")),A[e]=f,g=0;g<f.length;g++)k=f[g],void 0===B[k]&&(B[k]=g);a=A[a];b=[];for(d=0;d<c.length;d+=3)m=c[d],h=(e=d+1<c.length)?c[d+1]:0,k=(f=d+2<c.length)?c[d+2]:0,g=m>>2,m=(m&3)<<4|h>>4,h=(h&15)<<2|k>>6,k&=63,f||(k=64,e||(h=64)),b.push(a[g],a[m],a[h]||"",a[k]||"");c="https://pagead2.googlesyndication.com/pagead/gen_204?id=mys&d="+b.join("").replace(/\//g,
"_").replace(/\+/g,"-");a=window;if(b=a.navigator)b=a.navigator.userAgent,b=/Chrome/.test(b)&&!/Edge/.test(b)?!0:!1;b&&a.navigator.sendBeacon?a.navigator.sendBeacon(c):(a.google_image_requests||(a.google_image_requests=[]),b=a.document.createElement("img"),b.src=c,a.google_image_requests.push(b));this.a.a=[]}};function V(a,b){a.h||(S(a.a,32,b,4),a.b.forEach(function(c,d){S(a.a,31,c,d)}),a.c(),a.h=!0)}var W=new U,X=["mys","pingback"],Y=da;
X[0]in Y||"undefined"==typeof Y.execScript||Y.execScript("var "+X[0]);for(var Z;X.length&&(Z=X.shift());)X.length||void 0===W?Y[Z]&&Y[Z]!==Object.prototype[Z]?Y=Y[Z]:Y=Y[Z]={}:Y[Z]=W;}).call(this);
